### ISSUE TITLE
Install Alex asr

### ISSUE THREAD

**Issue by MatteoBotta** [UFAL-DSG/pykaldi2#1]
Hi,
I want install alex-asr to try online kaldi recognition, but after these commands: 
apt-get update
apt-get install -y build-essential libatlas-base-dev python-dev python-pip git wget gfortran g++ unzip zlib1g-dev automake autoconf libtool subversion
pip install Cython

when a try to install the script with Python2.7 system shows this error:

`running install
running bdist_egg
running egg_info
writing requirements to alex_asr.egg-info/requires.txt
writing alex_asr.egg-info/PKG-INFO
writing top-level names to alex_asr.egg-info/top_level.txt
writing dependency_links to alex_asr.egg-info/dependency_links.txt
reading manifest file 'alex_asr.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'alex_asr.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
It appears that the env is prepared. If there are errors, try deleting libs/ and rerunning the script.
echo alex_asr.a libs/kaldi/tools/openfst//src/lib/.libs/libfst.a libs/kaldi/src/online2/kaldi-online2.a libs/kaldi/src/ivector/kaldi-ivector.a libs/kaldi/src/nnet2/kaldi-nnet2.a libs/kaldi/src/lat/kaldi-lat.a libs/kaldi/src/decoder/kaldi-decoder.a libs/kaldi/src/cudamatrix/kaldi-cudamatrix.a libs/kaldi/src/feat/kaldi-feat.a libs/kaldi/src/transform/kaldi-transform.a libs/kaldi/src/gmm/kaldi-gmm.a libs/kaldi/src/thread/kaldi-thread.a libs/kaldi/src/hmm/kaldi-hmm.a libs/kaldi/src/tree/kaldi-tree.a libs/kaldi/src/matrix/kaldi-matrix.a libs/kaldi/src/util/kaldi-util.a libs/kaldi/src/base/kaldi-base.a > setup.py.add_libs
echo -msse -msse2 -Wall -pthread -DKALDI_DOUBLEPRECISION=0 -DHAVE_POSIX_MEMALIGN -Wno-sign-compare -Wno-unused-local-typedefs -Winit-self -DHAVE_EXECINFO_H=1 -rdynamic -DHAVE_CXXABI_H -DHAVE_ATLAS -g -Ilibs/kaldi/tools/openfst//include -Ilibs/kaldi/src -Ilibs/kaldi/tools/ATLAS/include -Ilibs/kaldi/tools/CLAPACK -Wno-sign-compare -I. -fPIC > setup.py.cxxflags_kaldi
echo "-Llibs/kaldi/tools/openfst//lib -Llibs/kaldi/tools/openfst//lib/fst" > setup.py.cxxflags_pyfst
skipping 'alex_asr/decoder.cpp' Cython extension (up-to-date)
cythoning alex_asr/fst/_fst.pyx to alex_asr/fst/_fst.cpp
## Error compiling Cython file:

...
        label_fst_map['**ROOT**'] = self
        for label, fst in label_fst_map.items():
            assert (not fst.osyms or fst.osyms == self.osyms) # output symbols must match
            label_id = self.osyms[label]
            label_fst_pairs.push_back(pair[int, libfst.ConstStdVectorFstPtr](label_id, fst.fst))
        libfst.Replace(label_fst_pairs, result.fst, self.osyms['**ROOT**'], epsilon)
##                      ^

alex_asr/fst/_fst.pyx:766:22: no suitable method found
## Error compiling Cython file:

...
        label_fst_map['**ROOT**'] = self
        for label, fst in label_fst_map.items():
            assert (not fst.osyms or fst.osyms == self.osyms) # output symbols must match
            label_id = self.osyms[label]
            label_fst_pairs.push_back(pair[int, libfst.ConstLogVectorFstPtr](label_id, fst.fst))
        libfst.Replace(label_fst_pairs, result.fst, self.osyms['**ROOT**'], epsilon)
##                      ^

alex_asr/fst/_fst.pyx:1407:22: no suitable method found
building 'alex_asr.fst._fst' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I. -Ilibs/kaldi/tools/openfst/include -Ilibs/kaldi/src -I/usr/include/python2.7 -c alex_asr/fst/_fst.cpp -o build/temp.linux-x86_64-2.7/alex_asr/fst/_fst.o -std=c++0x -Llibs/kaldi/tools/openfst//lib -Llibs/kaldi/tools/openfst//lib/fst
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
alex_asr/fst/_fst.cpp:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
 #error Do not use this file, it is the result of a failed Cython compilation.
  ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
`

Can you help me?

Thanks in advance 

Mat

**Comment by jurcicek** [comment]
You have on your system Cython version >= 24.

The code works only with Cython version <= 24.

Best regards,
Filip Jurcicek

---

Work tel. (CZ): +420221914402
Personal tel. (CZ): +420777805048
Skype: bozskyfilip

http://ufal.mff.cuni.cz/filip-jurcicek

**Comment by MatteoBotta** [comment]
Thank you,
Now Asr works correctly.
I have another question.
I don't understand how can i active online recognition?
I would transcribe microphone audio input.

Thanks in advance 

Mat

**Comment by jurcicek** [comment]
Well, alex-asr is only library accessing Kaldi decoders.

You must record audio on your own and feed it in the Kaldi using the
available programming  interface.

alex-asr is not stand alone program for online recognition.

Best regards,
Filip Jurcicek

---

Work tel. (CZ): +420221914402
Personal tel. (CZ): +420777805048
Skype: bozskyfilip

http://ufal.mff.cuni.cz/filip-jurcicek

**Comment by MatteoBotta** [comment]
Thanks

Best regards
Matteo
